andy_guitar_repair/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve


from andy_settings.base import STATIC_ROOT, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Static
    url(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    # Media Root
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # Site URLs
    url(r'', include('andy_site.urls'))
]

andy_site/urls.py
from django.conf.urls import url

from .views import get_landing, get_services, get_service, get_galley, get_robots, get_ssl, get_sitemap, get_htaccess

urlpatterns = [
    url(r'^$', get_landing, name='home'),

    url(r'services/$',get_services, name='services'),
    url(r'services/(?P<service_slug>[\w-]+)/$' , get_service, name='service'),

    url(r'project-gallery/$', get_galley, name='gallery'),

    url(r'.well-known/pki-validation/starfield.html', get_ssl),
    url(r'sitemap.xml', get_sitemap),
    url(r'robots.txt', get_robots),
    url(r'.htaccess', get_htaccess)
]

andy_site/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.timezone import now
from django.utils.text import slugify

from django.urls import reverse
import os

# Create your models here.



def upload_site_img(instance, filename):
    filename_base, filename_ext = os.path.splitext(filename)
    return '%s%s' % (
        filename_base,
        filename_ext.lower(),
    )



class About(models.Model):
    about = models.TextField()


    def __unicode__(self):
        return 'Info' + ' - ' + str(self.id)

    class Meta:
        verbose_name = 'About Text'
        verbose_name_plural = 'About Text'


class ImageContent(models.Model):
    text = models.TextField()


    def __unicode__(self):
        return 'Text' + ' - ' + str(self.id)

    class Meta:
        verbose_name = 'Image Text'
        verbose_name_plural = 'Image Texts'



class Service(models.Model):
    service = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to=upload_site_img)
    rank = models.IntegerField()

    slug = models.SlugField(
        default='',
        editable=False,
        max_length=200
    )

    def get_absolute_url(self):
        kwargs = {
            'pk': self.id,
            'slug': self.slug
        }
        return reverse('article-pk-slug-detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.service
        self.slug = slugify(value, allow_unicode=True)
        super(Service, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.service

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'



class PricingItem(models.Model):
    cate = models.ForeignKey(Service)
    name = models.CharField(max_length=300)
    price = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Service Price'
        verbose_name_plural = 'Service Prices'



class GalleryPost(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    image1 = models.ImageField(upload_to=upload_site_img)
    image2 = models.ImageField(upload_to=upload_site_img, blank=True, null=True)
    image3 = models.ImageField(upload_to=upload_site_img, blank=True, null=True)

    tag1 = models.CharField(max_length=200, blank=True, null=True)
    tag2 = models.CharField(max_length=200, blank=True, null=True)
    tag3 = models.CharField(max_length=200, blank=True, null=True)
    tag4 = models.CharField(max_length=200, blank=True, null=True)
    tag5 = models.CharField(max_length=200, blank=True, null=True)
    tag6 = models.CharField(max_length=200, blank=True, null=True)
    tag7 = models.CharField(max_length=200, blank=True, null=True)
    tag8 = models.CharField(max_length=200, blank=True, null=True)
    tag9 = models.CharField(max_length=200, blank=True, null=True)


    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = 'Gallery Post'
        verbose_name_plural = 'Gallery Posts'




class Testimonials(models.Model):
    client = models.CharField(max_length=200)
    location = models.CharField(max_length=300)
    testimonial = models.TextField()

    def __unicode__(self):
        return self.client

    class Meta:
        verbose_name = 'Testimonial'
        verbose_name_plural = 'Testimonials'



class ContactRequest(models.Model):

    name = models.CharField(max_length=100)
    number = models.CharField(max_length=100)
    email = models.EmailField()
    description = models.TextField()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'Contact Request'
        verbose_name_plural = 'Contact Request'


class ContactInfo(models.Model):
    name = models.CharField(max_length=200)
    number = models.CharField(max_length=200)
    email = models.CharField(max_length=400)
    facebook = models.CharField(max_length=500)
    youtube = models.CharField(max_length=500)


    def __unicode__(self):
        return 'My Contact Info'

    class Meta:
        verbose_name = 'Contact Info'
        verbose_name_plural = 'Contact Infos'

templates/contact/contact.html
{% load crispy_forms_tags %}
<section id="contact">

    <h1 class="title">Contact</h1>


    <div id="contact_info">
        <p>{{ contact_info.name }}</p>
        <p>{{ contact_info.number }}</p>
        <p id="email-contact">{{ contact_info.email }}</p>
    </div>


    <div id="call-form" class="page">
        <div>
            <form method="post">
                <div class="row">
                    {% csrf_token %}
                    {{ form|crispy }}
                </div>
                <input id="contactform-submit" type="submit" value="Submit">
            </form>
        </div>
    </div>

    <div id="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d19842.687274221313!2d0.6252344026941561!3d51.56207530708491!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8dbc9348e19d9%3A0x3b23c8ce5e6e46cf!2sThe+Fairway%2C+Southend-on-Sea%2C+Leigh-on-Sea!5e0!3m2!1sen!2suk!4v1557477503358!5m2!1sen!2suk" width="800" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>

    <script>
        $('#id_name').addClass('form-control');
        $('#id_number').addClass('form-control');
        $('#id_email').addClass('form-control');
        $('#id_description').addClass('form-control').css('height', '200px');

        $('#div_id_name').addClass('wrap-1');
        $('#div_id_number').addClass('wrap-1');
        $('#div_id_email').addClass('wrap-1');
        $('#contactform-submit').addClass('wrap-1');
        $('#div_id_description').addClass('wrap-2');

        $('.wrap-1').wrapAll('<div class=col-1>');
        $('.wrap-2').wrapAll('<div class=col-1>');
        $('.wrap-3').wrapAll('<div class=col-2>');
  </script>
</section>